---
title: "stl_lead_inequity"
author: "Daniel Kerstan"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 6, fig.height = 5)
library(here)
library(tidyverse)
library(janitor)
library(skimr)

stl_lead <- read_delim(here::here("data","stl_blood_lead.csv"), delim = ";")
```

clean up data names

```{r}
stl_lead <- stl_lead %>% clean_names()
stl_lead
skim(stl_lead)
summary(stl_lead)
names(stl_lead)
```

```{r}
stl_lead_prop <- data.frame(stl_lead)
stl_lead_prop <- dplyr::mutate(stl_lead_prop, prop_white = ((white / total_pop) * 100)) 
stl_lead_prop <- dplyr::mutate(stl_lead_prop, pct_elevated = str_replace(pct_elevated, pattern = ",", replacement = "."))

stl_lead_prop <- dplyr::mutate(stl_lead_prop, pct_elevated = as.numeric(pct_elevated)) 
```


```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) + geom_point(aes(color = pct_elevated))+ scale_color_gradient(low = "blue", high = "red") 

stl_lead_plot
```
The graph shows that as the percent elevated increases, the proportion of white decreases


```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), plot = stl_lead_plot, height = 5, width = 6)
```

```{r}
stl_lead_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram()

stl_lead_hist

ggsave(here::here("figs", "stl_lead_hist.jpg"), plot = stl_lead_hist, height = 5, width = 6)
```


